use airline;
create table cabin_class(rdate date, class char(10));
select * from cabin_class;
alter table cabin_class add column batch int(3);
create table login(username varchar(10),passwd varchar(10));
alter table location add column batch int(3);
alter table payment add column batch int(3);
alter table cabin_class add column batch int(3);
create table payment(cardno int(12),fullname char(10),expirydate date);
select * from login;
select * from payment;
create table feedback(sno int(2), review varchar(40), rate varchar(5));
select * from feedback;
create table refund(sno int(2), class char(10), refund int(12));
alter table refund drop sno;
alter table feedback drop sno;
desc refund;
desc payment; 
desc feedback;
show tables;